### PR TITLE
Support pip installation and fix py3 bugs

### PR DESCRIPTION
**Pull request by lukehsiao**
Allows other software to use treedlib by simply installing it as a package as part of their dependencies:

```
pip install git+https://github.com/HazyResearch/treedlib@master
```

rather than needing to include it as a git submodule.

### CODE REVIEW

**Comment by lukehsiao** [comment]
@ajratner This PR makes it a little cleaner to import treedlib in projects like snorkel as an actualy python package rather than as a git submodule. Pinging you for review.

**Comment by ajratner** [comment]
Hey this looks great, thanks for this!!  LGTM!

**Comment by lukehsiao** [comment]
You'll need to be the one to merge since I don't have write access here.

**Comment by ajratner** [comment]
Ah gotcha, merged and thanks again!

**Pull request merged**
